name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dockerize:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        docker build --no-cache -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest .
        docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
  
  deploy:
    runs-on: ubuntu-latest
    needs: dockerize
    permissions:
      contents: read
      packages: write

    steps:
    - name: Update Container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_ADDRESS }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.USER_PRIVATE_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          ls -l /home/azariata.my.id/.env

          docker stop rtm-client || true
          docker rm rtm-client || true
          docker rmi rtm-client || true
          docker pull ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
          docker image prune -f || true
          
          docker run -d \
            -p 8101:8101 \
            --network pdu-network \
            --name rtm-client \
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest